### ISSUE TITLE
Which Palm keyboard models is this likely to work with?

### ISSUE THREAD

**Issue by jkesselm** [pymo/ppk_bluetooth#1]
Since Palm changed the connector a few times, there are a couple of different generations of keyboard out there. Mine's from the Palm 3 days, I believe... Any chance your solution will work with it, or can be easily adapted to it?

Palm (tm) Portable Keyboard
Designed by Think Outside, Inc.
Carlsbad, CA, USA

S/N: A0PE15E1A0A2
P10802U

(Previous USB solutions, alas, did not offer a version compatible with this keyboard model, and I have enough other projects in progress that I'd rather not do a redesign myself.)

Thanks in advance!

**Comment by pymo** [comment]
Please see the README.md on the front page for supported models. Palm Universal connector is not supported due to its very small pitch. But others have tried to make an adapter for it using DIY PCBs. See https://hackaday.io/project/181800-palm-pilot-keyboard-bluetooth-conversion
